# -*- coding: utf-8 -*-
"""LeukemiaRL_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhTfZyX6qK5Ff24_h8caHf2mhm4DEla1
"""
import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# Cell 1: Bulletproof Install (Removes old Gym and fixes Numpy)

# Cell 0: Real-World Dataset Preprocessing (Leukemia Microarray)
import pandas as pd
import numpy as np

from sklearn.feature_selection import SelectKBest, f_classif

print("--- LOADING LEUKEMIA DATASET ---")

# 1. Load the dataset
# Since there are no standard column headers, we use header=None
df = pd.read_csv('leukemia_small.csv', header=None)

# 2. Extract Labels and Transpose Features
# The labels are in the very first row. The features are all the rows below it.
y_str = df.iloc[0].values
X_raw = df.iloc[1:].values.T.astype(float) # Transpose so rows=patients, cols=genes

# 3. Encode the Target Variable
# 'ALL' becomes Class 0 (Majority: 47 patients)
# 'AML' becomes Class 1 (Minority: 25 patients)
y_raw = np.where(y_str == 'ALL', 0, 1)

# 4. Filter down to the Top 30 Genes using ANOVA
# This removes the thousands of purely random/noisy genes
# so your RL-MFGWfs can focus on the most important 30.
selector = SelectKBest(score_func=f_classif, k=30)
X_filtered = selector.fit_transform(X_raw, y_raw)

# Get the original indices of these 30 genes so we know their names later
top_30_gene_indices = selector.get_support(indices=True)

print(f"Original Dataset Shape: {X_raw.shape[0]} patients, {X_raw.shape[1]} genes")
print(f"Filtered Dataset Shape: {X_filtered.shape[0]} patients, {X_filtered.shape[1]} selected genes")
print(f"Class Distribution    : ALL (0): {np.sum(y_raw==0)} | AML (1): {np.sum(y_raw==1)}")
print("Data successfully loaded into 'X_filtered' and 'y_raw'!")

# Cell 2: Imports and Hellinger Distance Filter
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from imblearn.metrics import geometric_mean_score
from stable_baselines3 import PPO
from stable_baselines3.common.env_checker import check_env

def hellinger_distance(feature_col, y):
    """Calculates Hellinger Distance to keep minority-class predictive features."""
    class_0 = feature_col[y == 0]
    class_1 = feature_col[y == 1]

    bins = np.histogram_bin_edges(feature_col, bins='auto')
    p, _ = np.histogram(class_0, bins=bins, density=True)
    q, _ = np.histogram(class_1, bins=bins, density=True)

    p = p + 1e-10
    q = q + 1e-10

    h_dist = (1.0 / np.sqrt(2.0)) * np.sqrt(np.sum((np.sqrt(p) - np.sqrt(q)) ** 2))
    return h_dist

def filter_features(X, y, top_k=10):
    """Discards noisy features while keeping those with high Hellinger scores."""
    scores = [hellinger_distance(X[:, i], y) for i in range(X.shape[1])]
    top_feature_indices = np.argsort(scores)[-top_k:]
    return X[:, top_feature_indices], top_feature_indices, scores

# Cell 3: The Environment (With Exploration Safety Net)
class FeatureGroupingEnv(gym.Env):
    def __init__(self, X, y, num_tasks=3):
        super(FeatureGroupingEnv, self).__init__()
        self.X = X
        self.y = y
        self.num_features = X.shape[1]
        self.num_tasks = num_tasks
        self.current_feature_idx = 0

        self.observation_space = spaces.Box(low=0, high=1, shape=(4,), dtype=np.float32)
        self.action_space = spaces.Discrete(self.num_tasks)

        self.feature_assignments = np.full(self.num_features, -1)
        self.selection_history = np.zeros(self.num_features)

        self.lambda_1, self.lambda_2, self.lambda_3, self.lambda_4 = 1.0, 0.5, 0.1, 2.0

    def _get_observation(self):
        f_idx = self.current_feature_idx
        np.random.seed(f_idx)
        f_importance = np.random.uniform(0.5, 1.0)

        f_redundancy = 0.0
        if self.current_feature_idx > 0:
            assigned_features = self.X[:, :self.current_feature_idx]
            current_f_data = self.X[:, f_idx]
            correlations = [np.abs(np.corrcoef(current_f_data, assigned_features[:, j])[0, 1])
                            for j in range(self.current_feature_idx)]
            f_redundancy = np.mean(correlations) if correlations else 0.0

        f_task_similarity = len(np.unique(self.feature_assignments[self.feature_assignments != -1])) / self.num_tasks
        f_history = self.selection_history[f_idx]

        return np.array([f_importance, f_redundancy, f_task_similarity, f_history], dtype=np.float32)

    def step(self, action):
        self.feature_assignments[self.current_feature_idx] = action
        self.selection_history[self.current_feature_idx] += 0.1

        self.current_feature_idx += 1
        done = self.current_feature_idx >= self.num_features

        reward = 0.0
        if done:
            reward = self._calculate_reward()

        observation = np.zeros(4, dtype=np.float32) if done else self._get_observation()
        return observation, reward, done, False, {}

    def _calculate_reward(self):
        total_gmean = 0.0
        total_redundancy = 0.0
        active_tasks = 0

        for t in range(self.num_tasks):
            task_indices = np.where(self.feature_assignments == t)[0]

            if len(task_indices) == 0:
                continue

            X_subset = self.X[:, task_indices]

            # --- THE SAFETY NET ---
            # If a task has fewer than 3 features, give it a flat baseline score
            # so the AI isn't terrified to start filling it up.
            if len(task_indices) < 3:
                total_gmean += 0.5 # Baseline "okay" score
                total_redundancy += 0.0
            else:
                knn = KNeighborsClassifier(n_neighbors=3)
                knn.fit(X_subset, self.y)
                y_pred = knn.predict(X_subset)
                total_gmean += geometric_mean_score(self.y, y_pred)

                corr_matrix = np.corrcoef(X_subset, rowvar=False)
                redundancy = np.nansum(np.triu(corr_matrix, k=1)) / (len(task_indices) + 1e-5)
                total_redundancy += redundancy

            active_tasks += 1

        if active_tasks == 0:
            return -20.0

        avg_gmean = total_gmean / active_tasks
        avg_redundancy = total_redundancy / active_tasks

        empty_task_penalty = (self.num_tasks - active_tasks) * 10.0
        c_complexity = (self.num_features / active_tasks) / self.num_features

        reward = (self.lambda_4 * avg_gmean) - (self.lambda_2 * avg_redundancy) - (self.lambda_3 * c_complexity) - empty_task_penalty
        return reward

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_feature_idx = 0

        # --- THE WARM START FIX ---
        # Instead of starting with all features unassigned (-1),
        # we randomly distribute them evenly across the 3 tasks to begin with!
        self.feature_assignments = np.random.randint(0, self.num_tasks, size=self.num_features)

        # Reset history
        self.selection_history = np.zeros(self.num_features)

        return self._get_observation(), {}

# Cell 4: Train with High Entropy (Exploration)
X_raw, y_raw = make_classification(n_samples=1000, n_features=50, n_informative=20,
                                   n_redundant=10, weights=[0.9, 0.1], random_state=42)

print("Filtering features to protect minority class...")
X_filtered, top_indices, scores = filter_features(X_raw, y_raw, top_k=30)

env = FeatureGroupingEnv(X_filtered, y_raw, num_tasks=3)

print("\nInitializing PPO Agent with HIGH EXPLORATION...")
# ent_coef=0.1 forces the AI to try chaotic new combinations
model = PPO("MlpPolicy", env, ent_coef=0.1, learning_rate=0.0005, verbose=0)

print("Starting Training (Give it 40,000 steps to explore)...")
model.learn(total_timesteps=100)
print("Training Complete!")

# Cell 5: Testing the Grouping Rules
obs, info = env.reset()
done = False

while not done:
    # deterministic=True ensures the agent picks its absolute best learned action
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, truncated, info = env.step(action)

print("--- RESULTS ---")
print("Features have been assigned to the following tasks:")
print(env.feature_assignments)
print(f"Final Reward Score: {reward:.4f}")

# Cell 6: The Complete MFGWfs Core (GWO + IGT Optimization) - FIXED
import numpy as np
import copy
from sklearn.neighbors import KNeighborsClassifier
from imblearn.metrics import geometric_mean_score

class MFGWfs:
    def __init__(self, X, y, rl_task_assignments, num_wolves=5, max_iter=10, rmp=0.3):
        self.X = X
        self.y = y
        self.task_assignments = rl_task_assignments
        self.num_tasks = len(np.unique(rl_task_assignments))
        self.num_wolves = num_wolves
        self.max_iter = max_iter
        self.rmp = rmp # Random Mating Probability (for IGT)

        self.tasks_features = {}
        self.populations = {}

        # Track Top 3 Wolves for each task
        self.alpha_pos, self.alpha_score = {}, {}
        self.beta_pos, self.beta_score = {}, {}
        self.delta_pos, self.delta_score = {}, {}

        for t in range(self.num_tasks):
            self.tasks_features[t] = np.where(self.task_assignments == t)[0]
            num_features = len(self.tasks_features[t])

            # Start wolves with random binary feature subsets
            self.populations[t] = np.random.randint(2, size=(self.num_wolves, num_features)).astype(float)

            # --- THE FIX IS HERE ---
            # Initialize ALL leader positions to zero arrays
            self.alpha_pos[t] = np.zeros(num_features)
            self.beta_pos[t] = np.zeros(num_features)
            self.delta_pos[t] = np.zeros(num_features)

            # Initialize leader scores to negative infinity
            self.alpha_score[t] = -np.inf
            self.beta_score[t] = -np.inf
            self.delta_score[t] = -np.inf

    def fitness_function(self, wolf_binary, task_id):
        """Cost-Sensitive G-mean Evaluation"""
        active_indices = np.where(wolf_binary >= 0.5)[0]
        if len(active_indices) == 0: return 0.0

        selected_cols = self.tasks_features[task_id][active_indices]
        if len(selected_cols) == 0: return 0.0

        X_subset = self.X[:, selected_cols]
        knn = KNeighborsClassifier(n_neighbors=3)
        knn.fit(X_subset, self.y)
        y_pred = knn.predict(X_subset)
        return geometric_mean_score(self.y, y_pred)

    def optimize(self):
        """The Main GWO Hunt with Implicit Genetic Transfer"""
        print("\n--- STARTING MFGWfs OPTIMIZATION ---")

        for iteration in range(self.max_iter):
            a = 2.0 - iteration * (2.0 / self.max_iter)

            for t in range(self.num_tasks):
                num_features = len(self.tasks_features[t])
                if num_features == 0: continue

                # 1. EVALUATE FITNESS & FIND LEADERS
                for i in range(self.num_wolves):
                    score = self.fitness_function(self.populations[t][i], t)

                    if score > self.alpha_score[t]:
                        self.delta_score[t], self.delta_pos[t] = self.beta_score[t], copy.deepcopy(self.beta_pos[t])
                        self.beta_score[t], self.beta_pos[t] = self.alpha_score[t], copy.deepcopy(self.alpha_pos[t])
                        self.alpha_score[t], self.alpha_pos[t] = score, copy.deepcopy(self.populations[t][i])
                    elif score > self.beta_score[t]:
                        self.delta_score[t], self.delta_pos[t] = self.beta_score[t], copy.deepcopy(self.beta_pos[t])
                        self.beta_score[t], self.beta_pos[t] = score, copy.deepcopy(self.populations[t][i])
                    elif score > self.delta_score[t]:
                        self.delta_score[t], self.delta_pos[t] = score, copy.deepcopy(self.populations[t][i])

            # 2. UPDATE WOLF POSITIONS (The Hunt)
            for t in range(self.num_tasks):
                num_features = len(self.tasks_features[t])
                if num_features == 0: continue

                for i in range(self.num_wolves):
                    for j in range(num_features):
                        r1, r2 = np.random.rand(), np.random.rand()
                        A1, C1 = 2 * a * r1 - a, 2 * r2
                        D_alpha = abs(C1 * self.alpha_pos[t][j] - self.populations[t][i][j])
                        X1 = self.alpha_pos[t][j] - A1 * D_alpha

                        r1, r2 = np.random.rand(), np.random.rand()
                        A2, C2 = 2 * a * r1 - a, 2 * r2
                        D_beta = abs(C2 * self.beta_pos[t][j] - self.populations[t][i][j])
                        X2 = self.beta_pos[t][j] - A2 * D_beta

                        r1, r2 = np.random.rand(), np.random.rand()
                        A3, C3 = 2 * a * r1 - a, 2 * r2
                        D_delta = abs(C3 * self.delta_pos[t][j] - self.populations[t][i][j])
                        X3 = self.delta_pos[t][j] - A3 * D_delta

                        new_pos = (X1 + X2 + X3) / 3.0

                        # --- IMPLICIT GENETIC TRANSFER (IGT) ---
                        if np.random.rand() < self.rmp and self.num_tasks > 1:
                            other_task = np.random.choice([x for x in range(self.num_tasks) if x != t])
                            # Make sure the other task isn't empty before trying to steal its genes
                            if len(self.tasks_features[other_task]) > 0:
                                random_gene = np.random.choice(self.alpha_pos[other_task])
                                new_pos = (new_pos + random_gene) / 2.0

                        sigmoid = 1.0 / (1.0 + np.exp(-10 * (new_pos - 0.5)))
                        self.populations[t][i][j] = 1 if sigmoid > np.random.rand() else 0

            # Find the best valid task to print progress
            best_t = 0
            for t_idx in range(self.num_tasks):
                if len(self.tasks_features[t_idx]) > 0:
                    best_t = t_idx
                    break
            print(f"Iteration {iteration+1}/{self.max_iter} Completed. Best Task {best_t} G-mean: {self.alpha_score[best_t]:.4f}")

        print("\n--- OPTIMIZATION FINISHED ---")

# Cell 7 & 8: Fully Scaled Robust CC Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_predict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from imblearn.metrics import geometric_mean_score
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler # <--- NEW IMPORT
import numpy as np
import copy
import time
import warnings
warnings.filterwarnings('ignore')

print("--- PHASE 2 & 3: FULLY SCALED ROBUST CO-EVOLUTION ---")

# 1. SPLIT THE DATA FIRST
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered, y_raw, test_size=0.3, random_state=42, stratify=y_raw
)

# 2. ASK RL FOR GROUPS
obs, info = env.reset()
done = False
while not done:
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, truncated, info = env.step(action)
final_rl_grouping = env.feature_assignments

# --- UPDATED MFGWfs CLASS ---
class MFGWfs_Scaled_CC:
    def __init__(self, X, y, rl_task_assignments, num_wolves=20, max_iter=30, rmp=0.3):
        self.X = X
        self.y = y
        self.total_features = X.shape[1]
        self.task_assignments = rl_task_assignments
        #self.num_tasks = len(np.unique(rl_task_assignments))
        self.num_tasks = 3
        self.num_wolves = num_wolves
        self.max_iter = max_iter
        self.rmp = rmp

        self.tasks_features = {}
        self.populations = {}
        self.alpha_pos, self.alpha_score = {}, {}
        self.beta_pos, self.beta_score = {}, {}
        self.delta_pos, self.delta_score = {}, {}

        for t in range(self.num_tasks):
            self.tasks_features[t] = np.where(self.task_assignments == t)[0]
            num_features = len(self.tasks_features[t])
            self.populations[t] = np.random.randint(2, size=(self.num_wolves, num_features)).astype(float)
            self.alpha_pos[t], self.beta_pos[t], self.delta_pos[t] = np.zeros(num_features), np.zeros(num_features), np.zeros(num_features)
            self.alpha_score[t], self.beta_score[t], self.delta_score[t] = -np.inf, -np.inf, -np.inf

    def fitness_function(self, wolf_binary, task_id):
        active_indices = np.where(wolf_binary >= 0.5)[0]
        selected_cols = list(self.tasks_features[task_id][active_indices])

        for other_task in range(self.num_tasks):
            if other_task != task_id and len(self.tasks_features[other_task]) > 0:
                best_mask = self.alpha_pos[other_task] >= 0.5
                if np.any(best_mask):
                    selected_cols.extend(self.tasks_features[other_task][best_mask])

        if len(selected_cols) == 0: return 0.0

        selected_cols = np.unique(selected_cols).astype(int)
        X_subset = self.X[:, selected_cols]

        # --- THE FIX: ADDED STANDARD SCALER ---
        model_pipeline = Pipeline([
            ('scaler', StandardScaler()),
            ('smote', SMOTE(random_state=42)),
            ('knn', KNeighborsClassifier(n_neighbors=5))
        ])

        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        y_pred_cv = cross_val_predict(model_pipeline, X_subset, self.y, cv=cv)

        gmean = geometric_mean_score(self.y, y_pred_cv)

        alpha_weight = 0.99
        feature_ratio = len(selected_cols) / self.total_features
        fitness = (alpha_weight * gmean) + ((1.0 - alpha_weight) * (1.0 - feature_ratio))

        return fitness

    def optimize(self):
        print("\n--- STARTING SCALED CO-EVOLUTIONARY HUNT ---")
        for iteration in range(self.max_iter):
            a = 2.0 - iteration * (2.0 / self.max_iter)
            for t in range(self.num_tasks):
                num_features = len(self.tasks_features[t])
                if num_features == 0: continue

                for i in range(self.num_wolves):
                    score = self.fitness_function(self.populations[t][i], t)
                    if score > self.alpha_score[t]:
                        self.delta_score[t], self.delta_pos[t] = self.beta_score[t], copy.deepcopy(self.beta_pos[t])
                        self.beta_score[t], self.beta_pos[t] = self.alpha_score[t], copy.deepcopy(self.alpha_pos[t])
                        self.alpha_score[t], self.alpha_pos[t] = score, copy.deepcopy(self.populations[t][i])
                    elif score > self.beta_score[t]:
                        self.delta_score[t], self.delta_pos[t] = self.beta_score[t], copy.deepcopy(self.beta_pos[t])
                        self.beta_score[t], self.beta_pos[t] = score, copy.deepcopy(self.populations[t][i])
                    elif score > self.delta_score[t]:
                        self.delta_score[t], self.delta_pos[t] = score, copy.deepcopy(self.populations[t][i])

            for t in range(self.num_tasks):
                num_features = len(self.tasks_features[t])
                if num_features == 0: continue

                for i in range(self.num_wolves):
                    for j in range(num_features):
                        r1, r2 = np.random.rand(), np.random.rand()
                        A1, C1 = 2 * a * r1 - a, 2 * r2
                        D_alpha = abs(C1 * self.alpha_pos[t][j] - self.populations[t][i][j])
                        X1 = self.alpha_pos[t][j] - A1 * D_alpha

                        r1, r2 = np.random.rand(), np.random.rand()
                        A2, C2 = 2 * a * r1 - a, 2 * r2
                        D_beta = abs(C2 * self.beta_pos[t][j] - self.populations[t][i][j])
                        X2 = self.beta_pos[t][j] - A2 * D_beta

                        r1, r2 = np.random.rand(), np.random.rand()
                        A3, C3 = 2 * a * r1 - a, 2 * r2
                        D_delta = abs(C3 * self.delta_pos[t][j] - self.populations[t][i][j])
                        X3 = self.delta_pos[t][j] - A3 * D_delta

                        new_pos = (X1 + X2 + X3) / 3.0

                        if np.random.rand() < self.rmp and self.num_tasks > 1:
                            other_task = np.random.choice([x for x in range(self.num_tasks) if x != t])
                            if len(self.tasks_features[other_task]) > 0:
                                random_gene = np.random.choice(self.alpha_pos[other_task])
                                new_pos = (new_pos + random_gene) / 2.0

                        sigmoid = 1.0 / (1.0 + np.exp(-10 * (new_pos - 0.5)))
                        new_binary = 1 if sigmoid > np.random.rand() else 0

                        if np.random.rand() < 0.05:
                            new_binary = 1 - new_binary

                        self.populations[t][i][j] = new_binary

            best_t = 0
            for t_idx in range(self.num_tasks):
                if len(self.tasks_features[t_idx]) > 0 and self.alpha_score[t_idx] > self.alpha_score[best_t]:
                    best_t = t_idx
            print(f"Iteration {iteration+1}/{self.max_iter} Completed. Best Fitness Score: {self.alpha_score[best_t]:.4f}")

# 3. RUN MFGWfs
mfgwfs_optimizer = MFGWfs_Scaled_CC(X=X_train, y=y_train, rl_task_assignments=final_rl_grouping, num_wolves=20, max_iter=30)
mfgwfs_optimizer.optimize()

print("\n--- ASSEMBLING FINAL SUPER-SUBSET ---")
combined_features = []
for t in range(mfgwfs_optimizer.num_tasks):
    if len(mfgwfs_optimizer.tasks_features[t]) > 0:
        best_wolf_mask = mfgwfs_optimizer.alpha_pos[t] == 1
        selected_by_task = mfgwfs_optimizer.tasks_features[t][best_wolf_mask]
        print(f"Task {t} Alpha Wolf contributed {len(selected_by_task)} features.")
        combined_features.extend(selected_by_task)

mfgwfs_features = np.unique(combined_features).astype(int)
print(f"Total Unique Features Assembled: {len(mfgwfs_features)}")

# 4. EVALUATION FUNCTION (UPDATED WITH PIPELINE)
def evaluate_features(feature_indices, model_name):
    start_time = time.time()
    X_train_sub, X_test_sub = X_train[:, feature_indices], X_test[:, feature_indices]

    # Using the exact same pipeline structure to prevent data leakage
    model_pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('smote', SMOTE(random_state=42)),
        ('knn', KNeighborsClassifier(n_neighbors=5))
    ])

    model_pipeline.fit(X_train_sub, y_train)
    y_pred = model_pipeline.predict(X_test_sub)

    exec_time = time.time() - start_time
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    gmean = geometric_mean_score(y_test, y_pred)

    print(f"\n[{model_name}]")
    print(f"Features Used : {len(feature_indices)}")
    print(f"Accuracy      : {acc:.4f} | G-mean: {gmean:.4f} | Exec Time: {exec_time:.4f}s")
    print(f"Precision     : {prec:.4f} | Recall: {rec:.4f} | F1-Score: {f1:.4f}")

# 5. RUN THE BENCHMARKS
print("\n--- FINAL BENCHMARK RESULTS ---")
evaluate_features(np.arange(X_train.shape[1]), "Baseline (Scaled + SMOTE + KNN - All 30 Features)")

if len(mfgwfs_features) > 0:
    evaluate_features(mfgwfs_features, "Proposed RL-MFGWfs (Scaled CC Super-Subset)")
else:
    print("\n[Proposed RL-MFGWfs] Failed to select any features.")

import numpy as np

print("--- YOUR 16 GOLDEN FEATURE INDICES ---")
print(mfgwfs_features)

# Save the indices to a text file
np.savetxt("RL_MFGWfs_Golden_Features.txt", mfgwfs_features, fmt="%d")
print("\nSuccess! Saved to 'RL_MFGWfs_Golden_Features.txt' in your Colab files.")

# Optional: If you have your original column names, uncomment and edit the line below:
# feature_names = original_dataframe.columns[:-1] # Exclude target column
# print("\nFeature Names:", feature_names[mfgwfs_features])

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

print("--- CROSS-MODEL GENERALIZATION TEST ---")

def evaluate_new_models(feature_indices, model, model_name):
    start_time = time.time()
    X_train_sub, X_test_sub = X_train[:, feature_indices], X_test[:, feature_indices]

    model_pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('smote', SMOTE(random_state=42)),
        ('classifier', model)
    ])

    model_pipeline.fit(X_train_sub, y_train)
    y_pred = model_pipeline.predict(X_test_sub)

    exec_time = time.time() - start_time
    acc = accuracy_score(y_test, y_pred)
    gmean = geometric_mean_score(y_test, y_pred)

    print(f"\n[{model_name} with {len(feature_indices)} Golden Features]")
    print(f"Accuracy  : {acc:.4f} | G-mean: {gmean:.4f} | Exec Time: {exec_time:.4f}s")

# --- THE SAFETY NET ---
if len(mfgwfs_features) > 0:
    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
    svm_model = SVC(kernel='rbf', random_state=42)

    evaluate_new_models(mfgwfs_features, rf_model, "Random Forest")
    evaluate_new_models(mfgwfs_features, svm_model, "Support Vector Machine")

    print("\n--- TRAINING FINAL PRODUCTION MODEL FOR WEB APP ---")
    
    import joblib
    
    final_features = mfgwfs_features
    X_final = X_filtered[:, final_features]
    y_final = y_raw

    final_scaler = StandardScaler()
    X_scaled = final_scaler.fit_transform(X_final)

    final_rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
    final_rf_model.fit(X_scaled, y_final)

    joblib.dump(final_rf_model, 'leukemia_rf_model.pkl')
    joblib.dump(final_scaler, 'leukemia_scaler.pkl')
    np.save('golden_features.npy', final_features)

    print("Model, scaler, and features saved successfully for Streamlit!")
else:
    print("\n[WARNING] The RL agent failed to find good features this run. Please run the script again to retry!")